use MSVServiceCenter;

CREATE ROLE SysAdminMVS;
CREATE ROLE WorkerMVS;
CREATE ROLE ClientMVS;

-- DB ADMIN ROLE
GRANT
BACKUP DATABASE,
BACKUP LOG,
CREATE DEFAULT,
CREATE FUNCTION,
CREATE PROCEDURE,
CREATE RULE,
CREATE TABLE,
CREATE VIEW,
DELETE,
SELECT,
INSERT,
UPDATE,
ALTER,
REFERENCES,
EXECUTE,
VIEW DEFINITION,
CONTROL,
TAKE OWNERSHIP
ON DATABASE::MSVServiceCenter TO SysAdminMVS;

-- DB Worker ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Position TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Worker TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Exam TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.PracticalExam TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.TransportVehicle TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.PracticalExam_TransportVehicle TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DriversLicense TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.TheoreticalExam TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Question TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Answer TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.TheoreticalExam_Question TO WorkerMVS;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.ClientAnswer TO WorkerMVS;


--DB Client ROLE 
GRANT SELECT ON dbo.MedCard TO ClientMVS;
GRANT SELECT ON dbo.DriversLicense TO ClientMVS;
GRANT SELECT ON dbo.Voucher TO ClientMVS;
GRANT SELECT ON dbo.ServiceCenter TO ClientMVS;
GRANT SELECT ON dbo.Address TO ClientMVS;

-- CREATE LOGINS
CREATE LOGIN SysAdminMVS WITH PASSWORD = 'AdminMVS';
CREATE LOGIN WorkerMVS WITH PASSWORD = 'WorkerMVS';
CREATE LOGIN ClientMVS WITH PASSWORD = 'ClientMVS';

-- CEATE USERS
CREATE USER Marry FOR LOGIN SysAdminMVS;
CREATE USER Anna FOR LOGIN WorkerMVS;
CREATE USER Tom FOR LOGIN ClientMVS;

-- ADD MEMBERS
ALTER ROLE SysAdminMVS ADD MEMBER Marry;
ALTER ROLE WorkerMVS ADD MEMBER Anna;
ALTER ROLE ClientMVS ADD MEMBER Tom;
